sonar.projectKey=ORDERENGINE
sonar.working.directory=C:\\projects\\orderengine\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\projects\\orderengine
sonar.pullrequest.cache.basepath=C:\\projects\\orderengine
sonar.sources=\
"C:\\projects\\orderengine\\OrderEngine.Tests\\obj\\OrderEngine.Tests.csproj.nuget.dgspec.json",\
"C:\\projects\\orderengine\\OrderEngine.Tests\\obj\\project.assets.json",\
"C:\\projects\\orderengine\\OrderEngine.Tests\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\projects\\orderengine\\OrderEngine.Tests\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\projects\\orderengine\\OrderEngine.Tests\\bin\\Debug\\net10.0\\MvcTestingAppManifest.json",\
"C:\\projects\\orderengine\\OrderEngine.Tests\\bin\\Debug\\net10.0\\OrderEngine.Api.deps.json",\
"C:\\projects\\orderengine\\OrderEngine.Tests\\bin\\Debug\\net10.0\\OrderEngine.Api.runtimeconfig.json",\
"C:\\projects\\orderengine\\OrderEngine.Tests\\bin\\Debug\\net10.0\\OrderEngine.Api.staticwebassets.endpoints.json",\
"C:\\projects\\orderengine\\OrderEngine.Tests\\bin\\Debug\\net10.0\\OrderEngine.Application.deps.json",\
"C:\\projects\\orderengine\\OrderEngine.Tests\\bin\\Debug\\net10.0\\OrderEngine.Domain.deps.json",\
"C:\\projects\\orderengine\\OrderEngine.Tests\\bin\\Debug\\net10.0\\OrderEngine.Infrastructure.deps.json",\
"C:\\projects\\orderengine\\OrderEngine.Tests\\bin\\Debug\\net10.0\\OrderEngine.Tests.deps.json",\
"C:\\projects\\orderengine\\OrderEngine.Tests\\bin\\Debug\\net10.0\\OrderEngine.Tests.runtimeconfig.json",\
"C:\\projects\\orderengine\\OrderEngine.Tests\\obj\\Debug\\net10.0\\MvcTestingAppManifest.json",\
"C:\\projects\\orderengine\\docker-compose.sonarqube.yml",\
"C:\\projects\\orderengine\\docker-compose.yml",\
"C:\\projects\\orderengine\\Dockerfile"

040F15A9-1BD7-4E68-A2D0-DAF2F27D5D44.sonar.projectKey=ORDERENGINE:040F15A9-1BD7-4E68-A2D0-DAF2F27D5D44
040F15A9-1BD7-4E68-A2D0-DAF2F27D5D44.sonar.projectName=OrderEngine.Domain
040F15A9-1BD7-4E68-A2D0-DAF2F27D5D44.sonar.projectBaseDir=C:\\projects\\orderengine\\OrderEngine.Domain
040F15A9-1BD7-4E68-A2D0-DAF2F27D5D44.sonar.sourceEncoding=utf-8
040F15A9-1BD7-4E68-A2D0-DAF2F27D5D44.sonar.tests=
040F15A9-1BD7-4E68-A2D0-DAF2F27D5D44.sonar.sources=\
"C:\\projects\\orderengine\\OrderEngine.Domain\\OrderAggregate.cs",\
"C:\\projects\\orderengine\\OrderEngine.Domain\\obj\\OrderEngine.Domain.csproj.nuget.dgspec.json",\
"C:\\projects\\orderengine\\OrderEngine.Domain\\obj\\project.assets.json",\
"C:\\projects\\orderengine\\OrderEngine.Domain\\bin\\Debug\\net10.0\\OrderEngine.Domain.deps.json"

040F15A9-1BD7-4E68-A2D0-DAF2F27D5D44.sonar.cs.analyzer.projectOutPaths=\
"C:\\projects\\orderengine\\.sonarqube\\out\\0"
040F15A9-1BD7-4E68-A2D0-DAF2F27D5D44.sonar.cs.roslyn.reportFilePaths=\
"C:\\projects\\orderengine\\.sonarqube\\out\\0\\Issues.json"
040F15A9-1BD7-4E68-A2D0-DAF2F27D5D44.sonar.cs.scanner.telemetry=\
"C:\\projects\\orderengine\\.sonarqube\\out\\0\\Telemetry.json"

040F15A9-1BD7-4E68-A2D0-DAF2F27D5D44.sonar.working.directory=C:\\projects\\orderengine\\.sonarqube\\out\\.sonar\\mod0
8D961DA4-495D-4ADD-9B53-182682D78D2C.sonar.projectKey=ORDERENGINE:8D961DA4-495D-4ADD-9B53-182682D78D2C
8D961DA4-495D-4ADD-9B53-182682D78D2C.sonar.projectName=OrderEngine.Application
8D961DA4-495D-4ADD-9B53-182682D78D2C.sonar.projectBaseDir=C:\\projects\\orderengine\\OrderEngine.Application
8D961DA4-495D-4ADD-9B53-182682D78D2C.sonar.sourceEncoding=utf-8
8D961DA4-495D-4ADD-9B53-182682D78D2C.sonar.tests=
8D961DA4-495D-4ADD-9B53-182682D78D2C.sonar.sources=\
"C:\\projects\\orderengine\\OrderEngine.Application\\obj\\OrderEngine.Application.csproj.nuget.dgspec.json",\
"C:\\projects\\orderengine\\OrderEngine.Application\\obj\\project.assets.json",\
"C:\\projects\\orderengine\\OrderEngine.Application\\bin\\Debug\\net10.0\\OrderEngine.Application.deps.json",\
"C:\\projects\\orderengine\\OrderEngine.Application\\LoggingBehavior.cs",\
"C:\\projects\\orderengine\\OrderEngine.Application\\OrderContracts.cs",\
"C:\\projects\\orderengine\\OrderEngine.Application\\ValidationBehavior.cs"

8D961DA4-495D-4ADD-9B53-182682D78D2C.sonar.cs.analyzer.projectOutPaths=\
"C:\\projects\\orderengine\\.sonarqube\\out\\1"
8D961DA4-495D-4ADD-9B53-182682D78D2C.sonar.cs.roslyn.reportFilePaths=\
"C:\\projects\\orderengine\\.sonarqube\\out\\1\\Issues.json"
8D961DA4-495D-4ADD-9B53-182682D78D2C.sonar.cs.scanner.telemetry=\
"C:\\projects\\orderengine\\.sonarqube\\out\\1\\Telemetry.json"

8D961DA4-495D-4ADD-9B53-182682D78D2C.sonar.working.directory=C:\\projects\\orderengine\\.sonarqube\\out\\.sonar\\mod1
BE58E27B-708D-4A05-9BE3-AF5FC61CEC64.sonar.projectKey=ORDERENGINE:BE58E27B-708D-4A05-9BE3-AF5FC61CEC64
BE58E27B-708D-4A05-9BE3-AF5FC61CEC64.sonar.projectName=OrderEngine.Infrastructure
BE58E27B-708D-4A05-9BE3-AF5FC61CEC64.sonar.projectBaseDir=C:\\projects\\orderengine\\OrderEngine.Infrastructure
BE58E27B-708D-4A05-9BE3-AF5FC61CEC64.sonar.sourceEncoding=utf-8
BE58E27B-708D-4A05-9BE3-AF5FC61CEC64.sonar.tests=
BE58E27B-708D-4A05-9BE3-AF5FC61CEC64.sonar.sources=\
"C:\\projects\\orderengine\\OrderEngine.Infrastructure\\obj\\OrderEngine.Infrastructure.csproj.nuget.dgspec.json",\
"C:\\projects\\orderengine\\OrderEngine.Infrastructure\\obj\\project.assets.json",\
"C:\\projects\\orderengine\\OrderEngine.Infrastructure\\bin\\Debug\\net10.0\\OrderEngine.Infrastructure.deps.json",\
"C:\\projects\\orderengine\\OrderEngine.Infrastructure\\Class1.cs",\
"C:\\projects\\orderengine\\OrderEngine.Infrastructure\\EfCoreOrderRepository.cs",\
"C:\\projects\\orderengine\\OrderEngine.Infrastructure\\InMemoryOrderRepository.cs",\
"C:\\projects\\orderengine\\OrderEngine.Infrastructure\\Migrations\\20260823033546_InitialCreate.cs",\
"C:\\projects\\orderengine\\OrderEngine.Infrastructure\\Migrations\\20260823033546_InitialCreate.Designer.cs",\
"C:\\projects\\orderengine\\OrderEngine.Infrastructure\\Migrations\\OrderDbContextModelSnapshot.cs",\
"C:\\projects\\orderengine\\OrderEngine.Infrastructure\\OrderDbContext.cs"

BE58E27B-708D-4A05-9BE3-AF5FC61CEC64.sonar.cs.analyzer.projectOutPaths=\
"C:\\projects\\orderengine\\.sonarqube\\out\\2"
BE58E27B-708D-4A05-9BE3-AF5FC61CEC64.sonar.cs.roslyn.reportFilePaths=\
"C:\\projects\\orderengine\\.sonarqube\\out\\2\\Issues.json"
BE58E27B-708D-4A05-9BE3-AF5FC61CEC64.sonar.cs.scanner.telemetry=\
"C:\\projects\\orderengine\\.sonarqube\\out\\2\\Telemetry.json"

BE58E27B-708D-4A05-9BE3-AF5FC61CEC64.sonar.working.directory=C:\\projects\\orderengine\\.sonarqube\\out\\.sonar\\mod2
0AF34CB3-42F1-4A35-A552-42878D7361C4.sonar.projectKey=ORDERENGINE:0AF34CB3-42F1-4A35-A552-42878D7361C4
0AF34CB3-42F1-4A35-A552-42878D7361C4.sonar.projectName=OrderEngine.Api
0AF34CB3-42F1-4A35-A552-42878D7361C4.sonar.projectBaseDir=C:\\projects\\orderengine\\OrderEngine.Api
0AF34CB3-42F1-4A35-A552-42878D7361C4.sonar.sourceEncoding=utf-8
0AF34CB3-42F1-4A35-A552-42878D7361C4.sonar.tests=
0AF34CB3-42F1-4A35-A552-42878D7361C4.sonar.sources=\
"C:\\projects\\orderengine\\OrderEngine.Api\\appsettings.Development.json",\
"C:\\projects\\orderengine\\OrderEngine.Api\\appsettings.json",\
"C:\\projects\\orderengine\\OrderEngine.Api\\obj\\OrderEngine.Api.csproj.nuget.dgspec.json",\
"C:\\projects\\orderengine\\OrderEngine.Api\\obj\\project.assets.json",\
"C:\\projects\\orderengine\\OrderEngine.Api\\Properties\\launchSettings.json",\
"C:\\projects\\orderengine\\OrderEngine.Api\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\projects\\orderengine\\OrderEngine.Api\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\projects\\orderengine\\OrderEngine.Api\\bin\\Debug\\net10.0\\OrderEngine.Api.deps.json",\
"C:\\projects\\orderengine\\OrderEngine.Api\\bin\\Debug\\net10.0\\OrderEngine.Api.runtimeconfig.json",\
"C:\\projects\\orderengine\\OrderEngine.Api\\bin\\Debug\\net10.0\\OrderEngine.Api.staticwebassets.endpoints.json",\
"C:\\projects\\orderengine\\OrderEngine.Api\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"C:\\projects\\orderengine\\OrderEngine.Api\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"C:\\projects\\orderengine\\OrderEngine.Api\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"C:\\projects\\orderengine\\OrderEngine.Api\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"C:\\projects\\orderengine\\OrderEngine.Api\\obj\\Debug\\net10.0\\staticwebassets.build.json",\
"C:\\projects\\orderengine\\OrderEngine.Api\\Auth\\JwtTokenService.cs",\
"C:\\projects\\orderengine\\OrderEngine.Api\\Endpoints\\OrderEndpoints.cs",\
"C:\\projects\\orderengine\\OrderEngine.Api\\Extensions\\BuilderExtensions.cs",\
"C:\\projects\\orderengine\\OrderEngine.Api\\Program.cs",\
"C:\\projects\\orderengine\\OrderEngine.Api\\obj\\Debug\\net10.0\\OrderEngine.Api.GlobalUsings.g.cs",\
"C:\\projects\\orderengine\\OrderEngine.Api\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"C:\\projects\\orderengine\\OrderEngine.Api\\obj\\Debug\\net10.0\\OrderEngine.Api.AssemblyInfo.cs",\
"C:\\projects\\orderengine\\OrderEngine.Api\\obj\\Debug\\net10.0\\OrderEngine.Api.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\projects\\orderengine\\OrderEngine.Api\\OrderEngine.Api.http",\
"C:\\projects\\orderengine\\OrderEngine.Api\\OrderEngine.db"

0AF34CB3-42F1-4A35-A552-42878D7361C4.sonar.cs.analyzer.projectOutPaths=\
"C:\\projects\\orderengine\\.sonarqube\\out\\3"
0AF34CB3-42F1-4A35-A552-42878D7361C4.sonar.cs.roslyn.reportFilePaths=\
"C:\\projects\\orderengine\\.sonarqube\\out\\3\\Issues.json"
0AF34CB3-42F1-4A35-A552-42878D7361C4.sonar.cs.scanner.telemetry=\
"C:\\projects\\orderengine\\.sonarqube\\out\\3\\Telemetry.json"

0AF34CB3-42F1-4A35-A552-42878D7361C4.sonar.working.directory=C:\\projects\\orderengine\\.sonarqube\\out\\.sonar\\mod3
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=040F15A9-1BD7-4E68-A2D0-DAF2F27D5D44,8D961DA4-495D-4ADD-9B53-182682D78D2C,BE58E27B-708D-4A05-9BE3-AF5FC61CEC64,0AF34CB3-42F1-4A35-A552-42878D7361C4

